name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  check_code_quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install isort black black[jupyter] flake8
      - name: Check quality
        run: |
          black . --line-length 79
          isort .
          flake8 . --max-line-length 79 --ignore=F405,F403
